[package]
name = "perftmaster"
version = "0.5.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
rand = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
vampirc-uci = "0.11.1"
